name: Build master

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - 'v*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:

      - name: Check out
        uses: actions/checkout@v3

      - name: Get time
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Build
        uses: tobyxdd/go-cross-build@d00fc41eb205f57dd90f6e5af4613e21c7ebe73f
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          CGO_ENABLED: "0"
        with:
          name: hysteria
          dest: dist
          ldflags: -w -s -X main.appCommit=${{ github.sha }} -X main.appDate=${{ env.TIME }}
          platforms: 'linux/amd64, linux/386, linux/arm, linux/arm64'
          package: cmd
          compress: false

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
